export const armadaList = [
  {
    id: 1,
    name: "Big Bus 001 Al Mubdi",
    imageFolder: "/images/armadas/Al Mubdi",
    type: "JetBus 2 HDD Adiputro",
    capacity: "48-59",
    price: "Rp 2.200.000",
    size: "big",
    facilities: [
      "Unit Fresh",
      "Bisa Request seat 2-3 atau 2-2",
      "AC",
      "Audio",
      "Smart TV",
      "Karaoke",
      "Charger",
      "Dispense",
    ],
  },
  {
    id: 2,
    name: "Big Bus 002 Al Qowiyyu",
    imageFolder: "/images/armadas/Al Qowiyyu",
    type: "JetBus 1 Single Glass Morodadi",
    capacity: "48-59",
    price: "Rp 2.200.000",
    size: "big",
    facilities: [
      "Unit Fresh",
      "Bisa Request seat 2-3 atau 2-2",
      "AC",
      "Audio",
      "Smart TV",
      "Karaoke",
      "Charger",
    ],
  },
  {
    id: 3,
    name: "Big Bus 003 Ar Razzaq",
    imageFolder: "/images/armadas/Ar Razzaq",
    type: "JetBus 3 HDD Adiputro",
    capacity: "48-59",
    price: "Rp 2.200.000",
    size: "big",
    facilities: [
      "Unit Fresh",
      "Bisa Request seat 2-3 atau 2-2",
      "AC",
      "Audio",
      "Smart TV",
      "Karaoke",
      "Charger",
      "Telolet",
    ],
  },
  {
    id: 4,
    name: "Big Bus 004 Al Fatih",
    imageFolder: "/images/armadas/Al Fatih",
    type: "Avante H9 Tentrem",
    capacity: "48-59",
    price: "Rp 2.200.000",
    size: "big",
    facilities: [
      "Unit Fresh",
      "Bisa Request seat 2-3 atau 2-2",
      "AC",
      "Audio",
      "Smart TV",
      "Karaoke",
      "Charger",
      "Telolet",
    ],
  },
  {
    id: 5,
    name: "Big Bus 007 Ar Rafah",
    imageFolder: "/images/armadas/Ar Rafah",
    type: "JetBus 3 HDD Adiputro",
    capacity: "48-59",
    price: "Rp 2.200.000",
    size: "big",
    facilities: [
      "Unit Fresh",
      "Bisa Request seat 2-3 atau 2-2",
      "AC",
      "Audio",
      "Smart TV",
      "Dispenser",
      "Karaoke",
      "Charger",
      "Telolet",
    ],
  },
  {
    id: 6,
    name: "Big Bus 008 Al Baa'its",
    imageFolder: "/images/armadas/Al Baa'its",
    type: "JetBus 3 HDD Adiputro",
    capacity: "48-59",
    price: "Rp 2.200.000",
    size: "big",
    facilities: [
      "Unit Fresh",
      "Bisa Request seat 2-3 atau 2-2",
      "AC",
      "Audio",
      "Smart TV",
      "Dispenser",
      "Karaoke",
      "Charger",
      "Telolet",
    ],
  },
  {
    id: 7,
    name: "Medium Bus 006 Al Mughni",
    imageFolder: "/images/armadas/Al Mughni",
    type: "JetBus 3 Medium Bus",
    capacity: "33-29",
    price: "Rp 1.500.000",
    size: "medium",
    facilities: [
      "Unit Fresh",
      "Bisa Request seat 2-3 atau 2-2",
      "AC",
      "Audio",
      "Smart TV",
      "Karaoke",
      "Charger",
    ],
  },
]
