export const armadaList = [
  {
    name: "Big Bus 001 Al Mubdi",
    image: "/images/armada-placeholder.jpg",
    type: "JetBus 2 HDD Adiputro",
    capacity: "48-59",
    price: "Rp 2.200.000",
    size: "big",
    facilities: [
      "Unit Fresh",
      "Bisa Request seat 2-3 atau 2-2",
      "AC",
      "Audio",
      "Smart TV",
      "Karaoke",
      "Charger",
      "Dispense",
    ],
  },
  {
    name: "Big Bus 002 Al Qowiyyu",
    image: "/images/armada-placeholder.jpg",
    type: "JetBus 1 Single Glass Morodadi",
    capacity: "48-59",
    price: "Rp 2.200.000",
    size: "big",
    facilities: [
      "Unit Fresh",
      "Bisa Request seat 2-3 atau 2-2",
      "AC",
      "Audio",
      "Smart TV",
      "Karaoke",
      "Charger",
    ],
  },
  {
    name: "Big Bus 003 Ar Razzaq",
    image: "/images/armada-placeholder.jpg",
    type: "JetBus 3 HDD Adiputro",
    capacity: "48-59",
    price: "Rp 2.200.000",
    size: "big",
    facilities: [
      "Unit Fresh",
      "Bisa Request seat 2-3 atau 2-2",
      "AC",
      "Audio",
      "Smart TV",
      "Karaoke",
      "Charger",
      "Telolet",
    ],
  },
  {
    name: "Big Bus 004 Al Fatih",
    image: "/images/armada-placeholder.jpg",
    type: "Avante H9 Tentrem",
    capacity: "48-59",
    price: "Rp 2.200.000",
    size: "big",
    facilities: [
      "Unit Fresh",
      "Bisa Request seat 2-3 atau 2-2",
      "AC",
      "Audio",
      "Smart TV",
      "Karaoke",
      "Charger",
      "Telolet",
    ],
  },
  {
    name: "Big Bus 007 Ar Rafah",
    image: "/images/armada-placeholder.jpg",
    type: "JetBus 3 HDD Adiputro",
    capacity: "48-59",
    price: "Rp 2.200.000",
    size: "big",
    facilities: [
      "Unit Fresh",
      "Bisa Request seat 2-3 atau 2-2",
      "AC",
      "Audio",
      "Smart TV",
      "Dispenser",
      "Karaoke",
      "Charger",
      "Telolet",
    ],
  },
  {
    name: "Big Bus 008 Al Baa'its",
    image: "/images/armada-placeholder.jpg",
    type: "JetBus 3 HDD Adiputro",
    capacity: "48-59",
    price: "Rp 2.200.000",
    size: "big",
    facilities: [
      "Unit Fresh",
      "Bisa Request seat 2-3 atau 2-2",
      "AC",
      "Audio",
      "Smart TV",
      "Dispenser",
      "Karaoke",
      "Charger",
      "Telolet",
    ],
  },
  {
    name: "Medium Bus 006 Al Mughni",
    image: "/images/armada-placeholder.jpg",
    type: "JetBus 3 Medium Bus",
    capacity: "33-29",
    price: "Rp 1.500.000",
    size: "medium",
    facilities: [
      "Unit Fresh",
      "Bisa Request seat 2-3 atau 2-2",
      "AC",
      "Audio",
      "Smart TV",
      "Karaoke",
      "Charger",
    ],
  },
]
